# -*- coding: utf-8 -*-
"""Customer Behaviour Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mdnv3_0zZGRusxhm9aicOjuyZdjyr_by
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

import os

os.listdir('/content')

import pandas as pd

df = pd.read_csv('/content/ecommerce_customer_data_large.csv')

df.head()

df.shape

df.columns

df.info()

df.isnull().sum()

df = df.dropna()

df.describe()

plt.figure(figsize=(6,4))
sns.countplot(x='Gender', data=df)

plt.title("Gender Distribution")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['Age'], bins=20)

plt.title("Age Distribution")

plt.show()

df.duplicated().sum()

df = df.drop_duplicates()

df.columns

df.head(10)

plt.figure(figsize=(10,6))

sns.heatmap(df.corr(numeric_only=True), annot=True)

plt.title("Correlation Heatmap")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['Total Purchase Amount'], bins=30)

plt.title("Purchase Amount Distribution")

plt.show()

high_value = df[df['Total Purchase Amount'] > 500]

high_value.head()

plt.figure(figsize=(8,5))

sns.countplot(x='Product Price', data=df)

plt.xticks(rotation=90)

plt.title("Product Price Purchase")

plt.show()