# -*- coding: utf-8 -*-
"""Sales Performance Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aoaxztny-aDTfyhwGiEdvZbKe3vYglly
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('Superstore_Sales.csv', encoding='latin1')
print(df.head())
print(df.info())

print("Missing values before cleaning:\n", df.isnull().sum())

df = df.dropna(subset=['Sales', 'Order_Date'])

df['Order_Date'] = pd.to_datetime(df['Order_Date'], dayfirst=True)

df = df.drop_duplicates()
df = df[df['Sales'] > 0]


total_revenue = df['Sales'].sum()
total_orders = df['Order_ID'].nunique()
aov = total_revenue / total_orders

print(f"Total Revenue: {total_revenue}")
print(f"Average Order Value: {aov}")

import matplotlib.pyplot as plt
import seaborn as sns


sns.set_theme(style="whitegrid")


df.groupby(df['Order_Date'].dt.to_period('M'))['Sales'].sum().plot(kind='line', figsize=(10, 5), marker='o')
plt.title('Monthly Sales Trend')
plt.ylabel('Total Sales')
plt.show()

plt.figure(figsize=(8, 5))
sns.barplot(data=df, x='Region', y='Sales', estimator=sum, errorbar=None)
plt.title('Sales by Region')
plt.show()

df['Order_Date'] = pd.to_datetime(df['Order_Date'], dayfirst=True, errors='coerce')
df['Month'] = df['Order_Date'].dt.month_name()

plt.figure(figsize=(12,6))
sns.boxplot(data=df, x='Month', y='Sales', palette='coolwarm', hue='Month', legend=False)
plt.title('Monthly Sales Seasonality')
plt.xticks(rotation=45)
plt.show()

top_products = df.groupby('Product_Name')['Sales'].sum().sort_values(ascending=False).head(10)
top_products.plot(kind='barh', figsize=(8, 6), color='skyblue')
plt.title('Top 10 Products by Sales')
plt.xlabel('Total Sales')
plt.ylabel('Product Name')
plt.gca().invert_yaxis() # To display the highest sales at the top
plt.show()

sns.countplot(data=df, x='Ship_Mode', palette='pastel', hue='Ship_Mode', legend=False)
plt.title('Preference of Shipping Modes')
plt.show()

pivot_df = df.pivot_table(index='Category', columns='Sub_Category', values='Sales', aggfunc='sum')

plt.figure(figsize=(12,8))
sns.heatmap(pivot_df, annot=True, cmap='RdYlGn', fmt='.0f')
plt.title('Sales Heatmap: Category vs Sub-Category')
plt.show()