# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_v0KolFMs1xkdVOmqDp7Rm54yBr-j_x
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
import os
print("Files in /content/:", os.listdir('/content/'))
df = pd.read_csv('/content/traffic.csv')
df.head()

print("Rows and Collumn:",df.shape)

print("\nColumns:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

df.drop_duplicates(inplace=True)

print("Shape after removing duplicates:")
print(df.shape)

print("Total Events:",len(df))

print("Unique Countries:",df['country'].nunique())

print("Unique Cities:",df['city'].nunique())

df['event'].value_counts().plot(kind='bar')

plt.title("Event Distribution")
plt.xlabel("Event")
plt.ylabel("Count")
plt.show()

df['country'].value_counts().head(10).plot(kind='bar')

plt.title("Top 10 Countries")
plt.xlabel("Country")
plt.ylabel("Traffic")
plt.show()

df['artist'].value_counts().head(10).plot(kind='bar')

plt.title("Top Artists")
plt.xlabel("Artist")
plt.ylabel("Count")
plt.show()

df['album'].value_counts().head(10).plot(kind='bar')

plt.title("Top Albums")
plt.xlabel("Album")
plt.ylabel("Count")
plt.show()

df['track'].value_counts().head(10).plot(kind='bar')

plt.title("Top Tracks")
plt.xlabel("Track")
plt.ylabel("Count")
plt.show()

df['date'] = pd.to_datetime(df['date'])

daily_traffic = df.groupby('date').size()

daily_traffic.plot(figsize=(10,5))

plt.title("Traffic Trend")
plt.xlabel("Date")
plt.ylabel("Number of Events")
plt.show()